#[path = "common/fake_auth.rs"]
pub mod fake_auth;
#[path = "common/fake_temp_storage.rs"]
pub mod fake_temp_storage;
#[path = "unit/domain/mod.rs"]
pub mod domain;
#[path = "unit/infrastructure/mod.rs"]
pub mod infrastructure;
#[path = "unit/application/mod.rs"]
pub mod application;
#[path = "unit/presentation/mod.rs"]
pub mod presentation;
